LastSessions<|||>1<|||>contentplan
LastActiveSession<|||>1<|||>contentplan
ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,10
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,0
ColWidths_frmTableEditor.listColumns<|||>1<|||>55,100,152,90,60,65,50,117,130,139,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>234,100,80,120,80
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3,4
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>200,80,100,80,80,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,420
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
MainWinOnMonitor<|||>3<|||>0
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,316
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,316,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,191
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,256
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>120,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>0,0
MainWinWidth<|||>3<|||>880
MainWinHeight<|||>3<|||>465
FileDialogEncoding_MainForm<|||>3<|||>0
querymemoheight<|||>3<|||>310
sqloutheight<|||>3<|||>197
CreateDbCollation<|||>1<|||>utf8mb4_0900_ai_ci
SQLFile0<|||>1<|||>C:\laragon\www\varklass\database.sql
Servers\contentplan\SessionCreated<|||>1<|||>2026-06-13 10:48:33
Servers\contentplan\Host<|||>1<|||>127.0.0.1
Servers\contentplan\WindowsAuth<|||>3<|||>0
Servers\contentplan\CleartextPluginEnabled<|||>3<|||>0
Servers\contentplan\User<|||>1<|||>root
Servers\contentplan\Password<|||>1<|||>2
Servers\contentplan\LoginPrompt<|||>3<|||>0
Servers\contentplan\Port<|||>1<|||>3306
Servers\contentplan\NetType<|||>3<|||>0
Servers\contentplan\Compressed<|||>3<|||>0
Servers\contentplan\LocalTimeZone<|||>3<|||>0
Servers\contentplan\QueryTimeout<|||>3<|||>30
Servers\contentplan\KeepAlive<|||>3<|||>20
Servers\contentplan\FullTableStatus<|||>3<|||>1
Servers\contentplan\Databases<|||>1<|||>
Servers\contentplan\Library<|||>1<|||>libmariadb.dll
Servers\contentplan\Comment<|||>1<|||>
Servers\contentplan\StartupScriptFilename<|||>1<|||>
Servers\contentplan\TreeBackground<|||>3<|||>536870911
Servers\contentplan\SSHtunnelActive<|||>3<|||>0
Servers\contentplan\SshExecutable<|||>1<|||>
Servers\contentplan\SSHtunnelHost<|||>1<|||>
Servers\contentplan\SSHtunnelHostPort<|||>3<|||>22
Servers\contentplan\SSHtunnelUser<|||>1<|||>
Servers\contentplan\SSHtunnelPassword<|||>1<|||>4
Servers\contentplan\SSHtunnelTimeout<|||>3<|||>4
Servers\contentplan\SSHtunnelPrivateKey<|||>1<|||>
Servers\contentplan\SSHtunnelPort<|||>3<|||>3307
Servers\contentplan\SSL_Active<|||>3<|||>0
Servers\contentplan\SSL_Key<|||>1<|||>
Servers\contentplan\SSL_Cert<|||>1<|||>
Servers\contentplan\SSL_CA<|||>1<|||>
Servers\contentplan\SSL_Cipher<|||>1<|||>
Servers\contentplan\SSL_Verification<|||>3<|||>2
Servers\contentplan\IgnoreDatabasePattern<|||>1<|||>
Servers\contentplan\LogFileDdl<|||>3<|||>0
Servers\contentplan\LogFileDml<|||>3<|||>0
Servers\contentplan\LogFilePath<|||>1<|||>C:\Users\ADISYAH INDAH\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\contentplan\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\contentplan\ConnectCount<|||>3<|||>5
Servers\contentplan\ServerVersion<|||>3<|||>80403
Servers\contentplan\LastConnect<|||>1<|||>2026-06-26 16:45:46
Servers\contentplan\lastUsedDB<|||>1<|||>contentplan
Servers\Laragon.MySQL\SessionCreated<|||>1<|||>2024-12-16 22:28:25
Servers\Laragon.MySQL\Host<|||>1<|||>127.0.0.1
Servers\Laragon.MySQL\WindowsAuth<|||>3<|||>0
Servers\Laragon.MySQL\CleartextPluginEnabled<|||>3<|||>0
Servers\Laragon.MySQL\User<|||>1<|||>root
Servers\Laragon.MySQL\Password<|||>1<|||>2
Servers\Laragon.MySQL\LoginPrompt<|||>3<|||>0
Servers\Laragon.MySQL\Port<|||>1<|||>3306
Servers\Laragon.MySQL\NetType<|||>3<|||>0
Servers\Laragon.MySQL\Compressed<|||>3<|||>0
Servers\Laragon.MySQL\LocalTimeZone<|||>3<|||>0
Servers\Laragon.MySQL\QueryTimeout<|||>3<|||>30
Servers\Laragon.MySQL\KeepAlive<|||>3<|||>20
Servers\Laragon.MySQL\FullTableStatus<|||>3<|||>1
Servers\Laragon.MySQL\Databases<|||>1<|||>
Servers\Laragon.MySQL\Library<|||>1<|||>libmariadb.dll
Servers\Laragon.MySQL\Comment<|||>1<|||>
Servers\Laragon.MySQL\StartupScriptFilename<|||>1<|||>
Servers\Laragon.MySQL\TreeBackground<|||>3<|||>536870911
Servers\Laragon.MySQL\SSHtunnelActive<|||>3<|||>0
Servers\Laragon.MySQL\SshExecutable<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelHost<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelHostPort<|||>3<|||>22
Servers\Laragon.MySQL\SSHtunnelUser<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelPassword<|||>1<|||>8
Servers\Laragon.MySQL\SSHtunnelTimeout<|||>3<|||>4
Servers\Laragon.MySQL\SSHtunnelPrivateKey<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelPort<|||>3<|||>3307
Servers\Laragon.MySQL\SSL_Active<|||>3<|||>0
Servers\Laragon.MySQL\SSL_Key<|||>1<|||>
Servers\Laragon.MySQL\SSL_Cert<|||>1<|||>
Servers\Laragon.MySQL\SSL_CA<|||>1<|||>
Servers\Laragon.MySQL\SSL_Cipher<|||>1<|||>
Servers\Laragon.MySQL\SSL_Verification<|||>3<|||>2
Servers\Laragon.MySQL\IgnoreDatabasePattern<|||>1<|||>
Servers\Laragon.MySQL\LogFileDdl<|||>3<|||>0
Servers\Laragon.MySQL\LogFileDml<|||>3<|||>0
Servers\Laragon.MySQL\LogFilePath<|||>1<|||>C:\Users\Leo\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\Laragon.MySQL\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\Laragon.MySQL\ConnectCount<|||>3<|||>1
Servers\Laragon.MySQL\ServerVersion<|||>3<|||>80403
Servers\Laragon.MySQL\LastConnect<|||>1<|||>2024-12-16 22:28:58
Servers\Laragon.MySQL\lastUsedDB<|||>1<|||>mysql
Servers\varklass\SessionCreated<|||>1<|||>2026-05-31 12:29:24
Servers\varklass\Host<|||>1<|||>127.0.0.1
Servers\varklass\WindowsAuth<|||>3<|||>0
Servers\varklass\CleartextPluginEnabled<|||>3<|||>0
Servers\varklass\User<|||>1<|||>root
Servers\varklass\Password<|||>1<|||>9
Servers\varklass\LoginPrompt<|||>3<|||>0
Servers\varklass\Port<|||>1<|||>3306
Servers\varklass\NetType<|||>3<|||>0
Servers\varklass\Compressed<|||>3<|||>0
Servers\varklass\LocalTimeZone<|||>3<|||>0
Servers\varklass\QueryTimeout<|||>3<|||>30
Servers\varklass\KeepAlive<|||>3<|||>20
Servers\varklass\FullTableStatus<|||>3<|||>1
Servers\varklass\Databases<|||>1<|||>
Servers\varklass\Library<|||>1<|||>libmariadb.dll
Servers\varklass\Comment<|||>1<|||>
Servers\varklass\StartupScriptFilename<|||>1<|||>
Servers\varklass\TreeBackground<|||>3<|||>536870911
Servers\varklass\SSHtunnelActive<|||>3<|||>0
Servers\varklass\SshExecutable<|||>1<|||>
Servers\varklass\SSHtunnelHost<|||>1<|||>
Servers\varklass\SSHtunnelHostPort<|||>3<|||>22
Servers\varklass\SSHtunnelUser<|||>1<|||>
Servers\varklass\SSHtunnelPassword<|||>1<|||>8
Servers\varklass\SSHtunnelTimeout<|||>3<|||>4
Servers\varklass\SSHtunnelPrivateKey<|||>1<|||>
Servers\varklass\SSHtunnelPort<|||>3<|||>3307
Servers\varklass\SSL_Active<|||>3<|||>0
Servers\varklass\SSL_Key<|||>1<|||>
Servers\varklass\SSL_Cert<|||>1<|||>
Servers\varklass\SSL_CA<|||>1<|||>
Servers\varklass\SSL_Cipher<|||>1<|||>
Servers\varklass\SSL_Verification<|||>3<|||>2
Servers\varklass\IgnoreDatabasePattern<|||>1<|||>
Servers\varklass\LogFileDdl<|||>3<|||>0
Servers\varklass\LogFileDml<|||>3<|||>0
Servers\varklass\LogFilePath<|||>1<|||>C:\Users\ADISYAH INDAH\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\varklass\ServerVersionFull<|||>1<|||>8.4.3 - MySQL Community Server - GPL
Servers\varklass\ConnectCount<|||>3<|||>3
Servers\varklass\ServerVersion<|||>3<|||>80403
Servers\varklass\LastConnect<|||>1<|||>2026-06-13 10:48:03
Servers\varklass\lastUsedDB<|||>1<|||>performance_schema
